### ISSUE TITLE
Database design

### ISSUE THREAD

**Issue by DanceParty** [DanceParty/sparkle#4]
Since we lost the original work, we just tried to quickly add what we remembered and will update with changes

![image](https://github.com/DanceParty/sparkle/assets/10778294/9c589d62-b47b-4780-ac2a-294a91ca385c)

**Comment by JeehyaeDance** [comment]
added `code: string` to Game table

**Comment by JeehyaeDance** [comment]
added `status: "setting up" | "in progress" | "finished"` to Game table

**Comment by JeehyaeDance** [comment]
added `role: "OWNER" | "PLAYER"` to player table

**Comment by DanceParty** [comment]
Need to add a Message table
